#
# ## Modified from the default `scss-lint` rules:
#
# https://raw.githubusercontent.com/brigade/scss-lint/master/config/default.yml
#
# Generally we want to treat everything with error level severity except in cases where we can't
# easily fix lints without fairly involved changes and testing.
#
# Detailed info about each rule can be found here:
#
# https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md
#
# Rules we've decided to leave as a warning instead of an error should have comments explaining why
# we have an opinion on the rule.
#

scss_files: '**/*.scss'

exclude: 'node_modules/**'

linters:
    BangFormat:
        enabled: true
        space_before_bang: true
        space_after_bang: false
        severity: error

    # Editor's note: We don't really use BEM in the first place.
    BemDepth:
        enabled: false
        max_elements: 1

    BorderZero:
        enabled: true
        convention: zero # 'zero' or `none`
        severity: error

    # Editor's note: Chained classes are more likely a symptom of legacy CSS. On fresh SCSS you'd
    # more likely end up with a nested selector preceded by an ampersand.
    ChainedClasses:
        enabled: false

    ColorKeyword:
        enabled: true
        severity: error

    # Editor's note: Your components should have a `_colors.scss` file where you define these.
    ColorVariable:
        enabled: true

    Comment:
        enabled: true
        style: silent
        severity: error

    DebugStatement:
        enabled: true
        severity: error

    DeclarationOrder:
        enabled: true
        severity: error

    # Editor's note: Requiring a comment is going to come in handy for the next person after you.
    DisableLinterReason:
        enabled: true
        severity: error

    DuplicateProperty:
        enabled: true
        severity: error

    ElsePlacement:
        enabled: true
        style: same_line # 'same_line' or 'new_line'
        severity: error

    EmptyLineBetweenBlocks:
        enabled: true
        ignore_single_line_blocks: true
        severity: error

    # Editor's note: If you need it for instructional purposes, just put a comment.
    EmptyRule:
        enabled: true
        severity: error

    ExtendDirective:
        enabled: false

    FinalNewline:
        enabled: true
        present: true
        severity: error

    HexLength:
        enabled: true
        style: long # 'short' or 'long'
        severity: error

    HexNotation:
        enabled: true
        style: lowercase # 'lowercase' or 'uppercase'
        severity: error

    HexValidation:
        enabled: true
        severity: error

    IdSelector:
        enabled: true

    # Editor's note: If you wanna override this you better have a pretty fucking compelling reason.
    ImportantRule:
        enabled: true
        severity: error

    ImportPath:
        enabled: true
        leading_underscore: false
        filename_extension: false
        severity: error

    Indentation:
        enabled: true
        allow_non_nested_indentation: false
        character: space # 'space' or 'tab'
        width: 4
        severity: error

    LeadingZero:
        enabled: true
        style: include_zero # 'exclude_zero' or 'include_zero'
        severity: error

    # Editor's note: Maybe it's helpful to group rules.
    MergeableSelector:
        enabled: true
        force_nesting: true

    NameFormat:
        enabled: true
        allow_leading_underscore: true
        convention: hyphenated_lowercase # 'hyphenated_lowercase' or 'camel_case', or 'snake_case', or a regex pattern

    # Editor's note: We tend to bump against this rule reasonably because of the way our style
    # style variations and flagging classes tend to work in practice. Deeply nested selectors on
    # their own are still a bad thing.
    NestingDepth:
        enabled: true
        max_depth: 5
        ignore_parent_selectors: false

    # Editor's note: Placeholder classes are great, but while we have all this legacy code, it's
    # fine to have this tool at our disposal.
    PlaceholderInExtend:
        enabled: true
        severity: error

    PrivateNaimgConvention:
        enabled: false

    PropertyCount:
        enabled: true
        include_nested: false
        max_properties: 10

    PropertySortOrder:
        enabled: true
        ignore_unspecified: false
        min_properties: 4
        order: smacss # https://github.com/brigade/scss-lint/blob/master/data/property-sort-orders/smacss.txt
        separate_groups: true

    PropertySpelling:
        enabled: true
        extra_properties: []
        disabled_properties: []
        severity: error

    PropertyUnits:
        enabled: true
        global: [
            'ch', 'em', 'ex', 'rem',                 # Font-relative lengths
            'cm', 'in', 'mm', 'pc', 'pt', 'px', 'q', # Absolute lengths
            'vh', 'vw', 'vmin', 'vmax',              # Viewport-percentage lengths
            'deg', 'grad', 'rad', 'turn',            # Angle
            'ms', 's',                               # Duration
            'Hz', 'kHz',                             # Frequency
            'dpi', 'dpcm', 'dppx',                   # Resolution
            '%']                                     # Other
        properties: {}
        severity: error

    # Editor's note: This would be better as an error, but our font icon mixins use single colons
    # for their pseudo-classes.
    PseudoElement:
        enabled: true

    # Editor's note: Do this with a nested selector preceded by an ampersand.
    QualifyingElement:
        enabled: true
        allow_element_with_attribute: false
        allow_element_with_class: false
        allow_element_with_id: false

    SelectorDepth:
        enabled: true
        max_depth: 4

    # Editor's note: Ugh, someday.
    SelectorFormat:
        enabled: true
        convention: hyphenated_lowercase # 'hyphenated_lowercase' or 'strict_BEM', or 'hyphenated_BEM', or 'snake_case', or 'camel_case', or a regex pattern

    Shorthand:
        enabled: true
        allowed_shorthands: [1, 2, 3]
        severity: error

    SingleLinePerProperty:
        enabled: true
        allow_single_line_rule_sets: false
        severity: error

    SingleLinePerSelector:
        enabled: true
        severity: error

    SpaceAfterComma:
        enabled: true
        style: one_space # 'one_space' or 'no_space', or 'at_least_one_space'
        severity: error

    SpaceAfterPropertyColon:
        enabled: true
        style: one_space # or 'one_space' or 'no_space', or 'at_least_one_space', or 'aligned'
        severity: error

    SpaceAfterPropertyName:
        enabled: true
        severity: error

    SpaceAfterVariableName:
        enabled: true
        severity: error

    SpaceAroundOperator:
        enabled: true
        style: one_space # 'one_space' or 'at_least_one_space', or 'no_space'
        severity: error

    SpaceBeforeBrace:
        enabled: true
        style: space # 'space' or 'new_line'
        allow_single_line_padding: true
        severity: error

    SpaceBetweenParens:
        enabled: true
        spaces: 0
        severity: error

    StringQuotes:
        enabled: true
        style: single_quotes # 'single_quotes' or 'double_quotes'
        severity: error

    TrailingSemicolon:
        enabled: true
        severity: error

    TrailingWhitespace:
        enabled: true
        severity: error

    TrailingZero:
        enabled: false
        severity: error

    TransitionAll:
        enabled: false

    UnnecessaryMantissa:
        enabled: true
        severity: error

    UnnecessaryParentReference:
        enabled: true
        severity: error

    UrlFormat:
        enabled: true

    UrlQuotes:
        enabled: true
        severity: error

    # Editor's note: Use some variables. If you're doing something that complains about this, we
    # probably have the thing you want already!
    VariableForProperty:
        enabled: true
        properties:
            - color
            - font
            - z-index

    # Editor's note: Let `autoprefixer` handle this.
    VendorPrefix:
        enabled: true
        identifier_list: base
        additional_identifiers: []
        excluded_identifiers: []
        severity: error

    ZeroUnit:
        enabled: true
        severity: error

    Compass::*:
        enabled: false
